apiVersion: v1
kind: Service
metadata:
  name: mail-service-svc
spec:
  type: ClusterIP
  selector:
    app: mail-service
  ports:
    - name: mail-service-api
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  labels:
    app: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - image: huahoangphuc/mail-service
          name: mail-service
          ports:
            - containerPort: 8080
